name: MapTools
load: POSTWORLD
version: 101
main: de.miraculixx.webServer.Main
api-version: 1.16
authors: [ Miraculixx ]
description: Map Builder Tools - Speed up your map creating process by multiple hours
website: https://mutils.net/
softdepend: [ "MUtils-Web" ]
libraries:
  - "org.jetbrains.kotlin:kotlin-stdlib:1.9.20"
  - "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.7.0-Beta"
  - "org.jetbrains.kotlinx:kotlinx-coroutines-jdk8:1.7.0-Beta"
  - "org.jetbrains.kotlinx:kotlinx-serialization-json:1.4.1"
  - "dev.jorel:commandapi-bukkit-kotlin:9.2.0"
  - "dev.jorel:commandapi-bukkit-shade:9.2.0"
  - "commons-codec:commons-codec:1.15"
  - "org.zeroturnaround:zt-zip:1.15"
  - "net.kyori:adventure-api:4.13.1"
  - "net.kyori:adventure-text-minimessage:4.13.1"
  - "net.kyori:adventure-text-serializer-plain:4.13.1"
  - "net.kyori:adventure-text-serializer-gson:4.13.1"
  - "net.kyori:adventure-text-serializer-legacy:4.13.1"
  - "de.miraculixx:kpaper:1.1.1"

